# Generated by Django 5.2.15 on 2026-09-24 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def cleanup_soft_deleted_rows(apps, schema_editor):
    """Older versions of the Google Calendar disconnect (and of the stale
    event cleanup) soft-deleted these rows. A soft-deleted connection still
    holds its user's OneToOne slot — reconnecting failed with an
    IntegrityError — and a soft-deleted synced event blocked the same
    (connection, issue) from syncing again. Their Google grant was already
    revoked, so they can simply go. Also backfill calendar_id, which older
    rows didn't record (they always lived in the dedicated calendar)."""
    GoogleCalendarConnection = apps.get_model("db", "GoogleCalendarConnection")
    SyncedCalendarEvent = apps.get_model("db", "SyncedCalendarEvent")

    SyncedCalendarEvent.objects.filter(deleted_at__isnull=False).delete()
    SyncedCalendarEvent.objects.filter(connection__deleted_at__isnull=False).delete()
    GoogleCalendarConnection.objects.filter(deleted_at__isnull=False).delete()

    for connection in GoogleCalendarConnection.objects.exclude(plane_calendar_id=""):
        SyncedCalendarEvent.objects.filter(connection=connection, calendar_id="").update(
            calendar_id=connection.plane_calendar_id
        )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0130_googledriveconnection_issuegoogledrivefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="calendar_per_project",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="color_by_priority",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="project_calendar_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="reminder_days_before",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="sync_project_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="sync_tokens",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="two_way_sync",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="watch_channels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="syncedcalendarevent",
            name="calendar_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="syncedcalendarevent",
            name="pushed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedcalendarevent",
            name="pushed_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedcalendarevent",
            name="pushed_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedcalendarevent",
            name="pushed_summary",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="IssueCalendarEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("google_event_id", models.CharField(max_length=1024)),
                ("calendar_id", models.CharField(max_length=255)),
                ("summary", models.CharField(blank=True, max_length=1024)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("all_day", models.BooleanField(default=False)),
                ("html_link", models.TextField(blank=True)),
                ("meet_link", models.TextField(blank=True)),
                ("attendees", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="db.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_calendar_events",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_calendar_events",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Calendar Event",
                "verbose_name_plural": "Issue Calendar Events",
                "db_table": "issue_calendar_events",
                "ordering": ("start",),
            },
        ),
        migrations.RunPython(cleanup_soft_deleted_rows, migrations.RunPython.noop),
    ]
